### PR TITLE
Added selfSSL option to fix https request rejection + og:description support + og:image relative path to absolute support

### PR DESCRIPTION
**Pull request by Ndrou**
To fix these errors : 
```
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

And for supporting meta `og:description`

### CODE REVIEW

**Comment by Ndrou** [comment]
Is this npm package not maintened anymore ?

**Comment by gabceb** [comment]
Yes it is. Sorry i missed this PR. Ill take a look later today

**Comment by Ndrou** [comment]
Added support for og:image relative path and added a test for og:description

**Comment by KenanSulayman** [comment]
Please merge!

**Comment by gabceb** [comment]
Published new version with bumped minor. Thanks all!

**Comment by KenanSulayman** [comment]
Thanks! :beers:

**Pull request merged**
